utils::globalVariables(c("segWords",
                         "userdf_t2h",
                         "userOneChar",
                         "userTwoChar",
                         "num_char",
                         "drugnames",
                         "two_char",
                         "optlist",
                         "word_list",
                         "entropy",
                         "final_dn",
                         "twoCharFilter",
                         "threeCharFilter",
                         "fourCharFilter",
                         "fiveCharFilter",
                         "threeChar",
                         "fourChar",
                         "fiveChar"))


